name: Trivy Docker Image Scan
on:
  push:
    branches:
      - main

jobs:
  trivy-scan:
    name: Scan Public Docker Image with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - name: Scan Public Docker Image with Trivy
        id: trivy-scan
        run: |
          trivy image --exit-code 1 --severity CRITICAL,HIGH nginx:latest > trivy-report.txt || true
          cat trivy-report.txt
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-report
          path: trivy-report.txt
